# Generated by Django 5.0.2 on 2024-02-28 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=255)),
                ('unit_description', models.CharField(max_length=255)),
                ('unit_specialization', models.CharField(choices=[('B', 'Bcom'), ('P', 'Procurement'), ('E', 'Entrepreneurship'), ('A', 'All')], default='A')),
                ('group', models.CharField(choices=[('A', 'Accounting'), ('F', 'Finance'), ('IS', 'Information Systems'), ('I', 'Insurance'), ('H', 'Human Resource'), ('M', 'Marketing'), ('C', 'Common Unit')], default='A')),
                ('unit_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.year')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_marks', models.PositiveIntegerField(null=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_images')),
                ('question_answer', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('E', 'Exam'), ('C', 'Cat')], default='E')),
                ('question_academic_year', models.PositiveIntegerField(null=True)),
                ('question_views', models.PositiveIntegerField(default=0)),
                ('question_up_votes', models.PositiveIntegerField(default=0)),
                ('question_down_votes', models.PositiveIntegerField(default=0)),
                ('question_created_at', models.DateTimeField(auto_now_add=True)),
                ('question_updated_at', models.DateTimeField(auto_now=True)),
                ('question_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.unit')),
                ('question_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.year')),
            ],
        ),
    ]
