# Generated by Django 5.0.2 on 2024-02-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payment_period',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('semester', 'Semester'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
    ]
